# image
FROM python:3.9
LABEL maintainer="erwing.forero@xpertgroup.co"

# dir
WORKDIR /budget-app

# Paste all project
COPY . .

# sripts
RUN pip install --upgrade pip && \
    pip --no-cache-dir install -r requirements.txt && \
    pipenv install --system --deploy

# execute project
CMD ["pipenv", "run", "/budget/main.py"]
