# image
FROM python:3.9
LABEL maintainer="erwing.forero@xpertgroup.co"

# dir
WORKDIR /budget-app

# Paste all project
COPY . ./budget-app


# sripts
RUN pip install --upgrade pip && \
    pip --no-cache-dir install -r requirements.txt && \
    pipenv install pipenv install $(test "$DJANGO_ENV" == production || echo "--dev") --deploy --system --ignore-pipfile --deploy --system --ignore-pipfile

# execute project
CMD ["pipenv", "run", "budget/main.py"]
