# image
FROM python:3.9

#limit object
FROM base AS python-deps 

# Paste all project
COPY ./ ./

# runtime
FROM base AS runtime 

# Copy virtual env from python-deps stage
COPY --from=python-deps /.venv /.venv
ENV PATH="/.venv/bin:$PATH"
